version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
    expose:
      - 4000:4000
    depends_on:
      - redis-server
  
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
